export {
  COMPANY_LOGO_STORAGE_KEY,
  COMPANY_ICON_STORAGE_KEY,
  COMPANY_CAROUSEL_IMAGE_1_STORAGE_KEY,
  COMPANY_CAROUSEL_IMAGE_2_STORAGE_KEY,
  COMPANY_CAROUSEL_IMAGE_3_STORAGE_KEY,
  COMPANY_PORTAL_BANNER_STORAGE_KEY,
  COMPANY_PORTAL_DESCRIPTION_STORAGE_KEY,
  COMPANY_PORTAL_ENABLED_STORAGE_KEY,
  COMPANY_PORTAL_OPENING_HOURS_STORAGE_KEY,
  COMPANY_PORTAL_SLOGAN_STORAGE_KEY,
  COMPANY_PORTAL_SLUG_STORAGE_KEY,
  COMPANY_PORTAL_SYNC_EVENT,
} from "@/services/company"
