export const COMPANY_LOGO_STORAGE_KEY = "mydashbarber.v1.logoUrl"
export const COMPANY_ICON_STORAGE_KEY = "mydashbarber.v1.iconUrl"
export const COMPANY_CAROUSEL_IMAGE_1_STORAGE_KEY = "mydashbarber.v1.carouselImage1"
export const COMPANY_CAROUSEL_IMAGE_2_STORAGE_KEY = "mydashbarber.v1.carouselImage2"
export const COMPANY_CAROUSEL_IMAGE_3_STORAGE_KEY = "mydashbarber.v1.carouselImage3"
